version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@2.0.1

jobs:
  build-and-test:
    resource_class: medium+
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: python -m unittest main.py -v
      - run: flake8 main.py --max-line-length=128 --count --statistics --show-source

  dockerize:
    executor: docker/docker
    resource_class: medium+
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/build:
          image: idme/hello-world
          tag: latest

workflows:
  version: 2
  hello-world:
    triggers:
      - schedule:
          cron: '15 * * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - build-and-test
      - dockerize:
          requires:
              - build-and-test
