name: Hello World

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branhces: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install deps
        run: python -m pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest test -v

      - name: Run Linting
        run: flake8 main.py --max-line-length=128 --count --statistics --show-source
      
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: hello-world:latest